### ISSUE TITLE
Add new project

### ISSUE THREAD

**Issue by sv-widegreen** [sv-widegreen/capstone-project#1]

**Comment by sv-widegreen** [comment]
### Value statement
---

As a sewer
I need an overview of my current project
so that I can easily pick it up again

### Description (Text, Scribble, Wireframe, Design)
---

Adding a new project with Input for "Project Name", "Pattern", "Size", "Next Steps"
<img width="288" alt="new_project" src="https://user-images.githubusercontent.com/65187225/86227454-53447680-bb8d-11ea-89b2-cde0bff6f1a4.png">

- no Dashboard Button or Navigation needed
- no pens next to input fields
- placeholder in 60% opacity

### Acceptance criteria
---

- [ ] Headline "New Project" and line underneath are fixed position
- [ ] Input writing left align in input field
- [ ] Blinking input line when clicked on input field
- [ ] Click on submit button sends inputs to bottom of page, new entrys added directly beneath input form, above the older entries

### Tasks
---
- [ ] install up and formik
- [ ] Create feature branch
- [ ] Create components (New Project Input, Project Entry) in Storybook

- [ ] Write component tests
- [ ] Add components to app (feature implementation with state)
- [ ] Add styles
- [ ] Write integration tests w/ Cypress
- [ ] Validate entries, only strings max length so that it does not break lines

### Size
---
medium
