### ISSUE TITLE
Add local storage

### ISSUE THREAD

**Issue by sv-widegreen** [sv-widegreen/capstone-project#3]

**Comment by sv-widegreen** [comment]
### Value statement
---

As a sewer
I need to be able to save all current projects
so that I can close the app and keep the latest status

### Description (Text, Scribble, Wireframe, Design)
---


### Acceptance criteria
---

- [ ] save all inputs to local storage separately

### Tasks
---
- [ ] Create feature branch
- [ ] Create component save to and load from local storage
- [ ] Write integration tests w/ Cypress
- [ ] Validate entries before loading

### Size
---
small
