### ISSUE TITLE
Add editing function

### ISSUE THREAD

**Issue by sv-widegreen** [sv-widegreen/capstone-project#4]

**Comment by sv-widegreen** [comment]
### Value statement
---

As a sewer
I need to be able to keep track of the status a project is in
so that I can easily pick it up again

### Description (Text, Scribble, Wireframe, Design)
---

click on an editing pen in the top right corner will change text to input fields and a save button appears below the next step entry

### Acceptance criteria
---

- [ ] click on editing pen will transform the text to input fields again
- [ ] Input writing left align in input field
- [ ] Blinking input line when clicked on input field, not when not in focus
- [ ] same validating as for the initial inputs
- [ ] Click on save button closes editing status and updates local storage

### Tasks
---
- [ ] Create feature branch
- [ ] Create component editing status in storybook
- [ ] Connect with local storage & state
- [ ] Write component tests
- [ ] Add components to app
- [ ] Add styles
- [ ] Write integration tests w/ Cypress
- [ ] Validate entries, same as before

### Size
---
large
