### ISSUE TITLE
Add material list

### ISSUE THREAD

**Issue by sv-widegreen** [sv-widegreen/capstone-project#5]
### Value statement
---

As a sewer
I need to know what materials I need
so that I know what to buy and don't buy too less/many.

### Description (Text, Scribble, Wireframe, Design)
---

Adding a new Input for "materials" as an Array/Todo List

### Acceptance criteria
---

- [x] Input writing left align in input field = textarea
- [x] Material List will be positioned beneath status in Form and Project List Overview
Validation:
- [x] length max 200

### Tasks
---
- [ ] Create feature branch
- [ ] Create components (material list) in Storybook
- [ ] Write component tests
- [ ] Add components to app (feature implementation with state)
- [ ] Add styles
- [ ] Write integration tests w/ Cypress
- [ ] Validate entries, only strings max length so that it does not break lines. Project name required.

### Size
---
small

**Comment by sv-widegreen** [comment]
### Value statement
---

As a sewer
I need an overview of my current project
so that I can easily pick it up again

### Description (Text, Scribble, Wireframe, Design)
---

Adding a new Input for "materials"

### Acceptance criteria
---

- [ ] Input writing left align in input field
- [ ] Blinking input line when clicked on input field, not when not in focus
- [ ] plus button on the right will add a new input field beneath the last, focus jumps here with blinking input line


### Tasks
---
- [ ] Create feature branch
- [ ] add input field materials with plus button on the right (mapping over initial empty string array)
- [ ] Create components (material list) in Storybook
- [ ] Write component tests
- [ ] Add components to app (feature implementation with state)
- [ ] Add styles
- [ ] Write integration tests w/ Cypress
- [ ] Validate entries, only strings max length so that it does not break lines. Project name required.

### Size
---
medium
