### ISSUE TITLE
Appdesign rework

### ISSUE THREAD

**Issue by sv-widegreen** [sv-widegreen/capstone-project#6]
### Value statement
---

As a sewer
I need a short overview of my current project first thing
so that I can easily scroll through all projects and see at a glance where they're at

### Description (Text, Scribble, Wireframe, Design)
---
Adding a Welcome screen with new logo
Adding a project overview page
floating plus button jumps to add new project form
submit jumps back to project overview page
no initial project - show add new form instead of project overview

### Acceptance criteria
---

- [x] welcome page with happy sewing button
- [x] clicking on happy sewing button will jump to project overview page
- [x] scroll through project overviews
- [x] floating add button that jumps to add new project form
- [x] if initially no projects - show add new project form as start page instead of project overview page

### Tasks
---
- [x] Create feature branch
- [x] Create component Project Overview Page and welcome screen in Storybook
- [x] remove projects from underneath input form on new project page
- [x] Write component tests
- [x] Add components to app
- [x] Add styles
- [x] Write integration tests w/ Cypress

### Size
---
medium

**Comment by sv-widegreen** [comment]
### Value statement
---

As a sewer
I need a short overview of my current project
so that I can easily scroll through all projects and see at a glance where they're at

### Description (Text, Scribble, Wireframe, Design)
---

Adding a project overview page
plus button on bottom of page jumps to new project inputs


### Acceptance criteria
---

- [ ] page will show only project name and next step
- [ ] clicking on a project will open product page, that I can edit and where I see all details now

### Tasks
---
- [ ] Create feature branch
- [ ] Create component Project Overview Page and Project Details page in Storybook
- [ ] remove projects from underneath input form on new project page
- [ ] Write component tests
- [ ] Add components to app
- [ ] Add styles
- [ ] Write integration tests w/ Cypress

### Size
---
large
